---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timber-backend
  labels:
    app: timber-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timber-backend
  template:
    metadata:
      labels:
        app: timber-backend
    spec:
      containers:
      - name: timber-backend
        image: eu.gcr.io/container-solutions-workshops/timber/backend:v1.0
        ports:
        - containerPort: 8080
