---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timber-backend
  labels:
    app: timber-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timber-backend
  template:
    metadata:
      labels:
        app: timber-backend
    spec:
      volumes:
      - name: "secret"
        secret:
          secretName: mysecret        
      containers:
      - name: timber-backend
        image: registry.gitlab.com/containersolutions/timber/backend
        ports:
        - containerPort: 8080
        env:
        - {name: TIMBER_READINESS_PROBE_ENABLED, value: "yep"}
        ports:
        - containerPort: 8080
        volumeMounts:
          - mountPath: "/tmp/secret"                
            name: "secret"
        readinessProbe:
            httpGet:
                path: /probe/readiness
                port: 8080
                scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 2
