---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timber-debugging
  labels:
    app: timber-debugging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timber-debugging
  template:
    metadata:
      labels:
        app: timber-debugging
    spec:
      containers:
      - name: timber-debugging
        image: registry.gitlab.com/containersolutions/timber/backend
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Gi"
            cpu: "500m"
          limits:
            memory: "128Gi"
            cpu: "100m"
