apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-stop-ingress
  namespace: user1          
spec:
  podSelector:
    matchLabels:
      app: timber-backend
  policyTypes:
  - Ingress
